version: "3.9"

services:
  service-a:
    build:
      context: ../backends/python-fastapi/service-a
    container_name: service-a
    networks:
      - kong-net

  service-b:
    build:
      context: ../backends/python-fastapi/service-b
    container_name: service-b
    networks:
      - kong-net

  kong:
    image: kong:3.6
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_STATUS_LISTEN: 0.0.0.0:8100
      KONG_PLUGINS: bundled,prometheus
    volumes:
      - ../kong/kong.yml:/kong/kong.yml
    ports:
      - "8000:8000"   # Kong proxy
      - "9001:8001"   # Kong admin (lab only)
      - "9100:8100"   # Kong status
    depends_on:
      - service-a
      - service-b
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
